version: "3"

services:
  data-base:
    extends:
      file: "./docker-compose/docker-compose.data-base.yml"
      service: data-base
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    extends:
      file: "./docker-compose/docker-compose.api.yml"
      service: api
    links:
      - data-base
    depends_on:
      data-base:
        condition: "service_healthy"

volumes:
  achivmenter_bd_vol:

networks:
  data-base-network:
    driver: "bridge"
