version: "3"

services:
  api:
    build:
      context: ../
      dockerfile: Dockerfile

    ports:
      - published: ${API_PORT}
        target: ${API_PORT}
    container_name: api-container
    restart: always

    networks:
      - data-base-network
    env_file:
      - ../.env