version: "3"

services:
  data-base:
    image: "postgres:13"
    ports:
      - published: ${DB_PORT}
        target: ${DB_PORT}
    container_name: ${DB_HOST}
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "bd_vol:/var/lib/postgresql/data"
    networks:
      - data-base-network
    env_file:
      - ../.env